# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node.
# After a successful build and test, it will push the main branch to the release branch.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
    push:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x, 20.x, 22.x]

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - run: npm ci
            - run: npm install --include=optional sharp
            - run: npm install --os=linux --cpu=x64 sharp
            - run: npm run build --if-present
            - run: npm test

    release:
        #needs: build
        #if: success()
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: Merge main -> release
              uses: devmasx/merge-branch@master
              with:
                  type: now
                  target_branch: release
                  github_token: ${{ secrets.GITHUB_TOKEN }}
